### ISSUE TITLE
[Question] Model Blocking / FPP Autoblock

### ISSUE THREAD

**Issue by guerryer** [LuaTenshi/APAnti#1]
Can you re-add the Model Blocking Code again ?

**Comment by LuaTenshi** [comment]
Sorry for the long response delay. But I can not re-add an auto model blocking.

Because the one I had was very glitchy and not always correct, and allot of people were blaming it on FPP for some reason and this was causing issues for another developer.

I may remake a code but it will not be added until there is a really good way to check if a prop is big or not the second it spawns or before it spawns. (There isn't one currently.)

**Comment by guerryer** [comment]
Ok Thanks for the response :)
